name: Build Docker Image

on:
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build and push Docker image
      env:
        RELEASE_VERSION: ${{ github.event.release.tag_name }}
      run: |
        docker build -t kaizen-app:$RELEASE_VERSION .
        docker tag kaizen-app:$RELEASE_VERSION ${{ secrets.DOCKER_USERNAME }}/kaizen-app:$RELEASE_VERSION
        docker push ${{ secrets.DOCKER_USERNAME }}/kaizen-app:$RELEASE_VERSION